ALTER TABLE rooms 
ADD COLUMN creator_id INT DEFAULT NULL,
ADD COLUMN is_started BOOLEAN DEFAULT FALSE,
ADD CONSTRAINT fk_room_creator
FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE SET NULL;
